
import Layout2 from "./layout2";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};


export default function RootLayout({ children }) {

  
  return (
    <html lang="en">
      <body>
        <Layout2 childern={children}/>
      </body>
    </html>
  );
}
